// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/************************************************************/
/**
 * 
 */
public class Game {

	private Board board;
	private List<Player> players;
	private int currentPlayer;
	private Dice dice;
	private int maxRounds;
    private int currentRound;
    private int mode;
    private Random rng;
    private int action;

	public Game(int mode){
		this.board = new Board();
        this.players = new ArrayList<>();
        this.currentPlayer = 0;
        this.dice = new Dice();

        this.maxRounds = 30;
        this.currentRound = 1;
        this.mode= mode;
        this.rng = new Random();
	}
	public void startGame(){
        if(mode ==1){
            for (int i = 0; i < 4; i++) {
                players.add(new Player(i));
            }
        } else if (mode ==2) {
            players.add(new HumanPlayer(1));
            for (int i = 2; i < 3; i++) {
                players.add(new Player(i));
            }
        }
        board.addTile(1, new Tile(1, "WOOD", 6));
        board.addTile(2, new Tile(2, "BRICK", 8));
        board.addTile(3, new Tile(3, "SHEEP", 9));

        for (int i = 1; i <= 6; i++) {
            board.addNode(i, new Node(i));
			board.addEdge(i, new Edge(i));
        }


        //main simulation loop
        while (currentRound<=maxRounds && !checkWin()){

            for (int i = 0; i < players.size(); i++) {
                currentPlayer = i;
                nextTurn();
                if (checkWin()) {
                    break;
                }
            }

            System.out.println("=== End of Round " + currentRound + " ===");
            for (int i=0; i<players.size(); i++) {
                System.out.println("Player " + i + " score: " + players.get(i).getScore());
            }
            System.out.println();

            currentRound++;
        }

        System.out.println("=== GAME OVER ===");
        for (int i = 0; i < players.size(); i++) {
            System.out.println("Player " + i + " final score: " + players.get(i).getScore());
        }

        }


	/**
	 * 
	 */
	public void nextTurn() {
		 Player p = players.get(currentPlayer);


        int roll = dice.roll();
        System.out.println("[Round " + currentRound + "] Player " + currentPlayer + " rolled " + roll);

        // simplified resource distribution:
        // if a tile matches the roll, current player gains 1 resource of that tile type
        for (int id = 1; id <= 3; id++) {
            Tile t = board.getTile(id);
            if (t != null && t.getDiceVal() == roll) {
                p.addResources(t.getResourceType(), 1);
                System.out.println("Player " + currentPlayer + " gets 1 " + t.getResourceType());
            }
        }
        if(!(p instanceof HumanPlayer)){
            action = rng.nextInt(3);
        }
        else{

            action = ((HumanPlayer) p).askForaction();
        }


        if (action == 0){
            boolean paidWood = p.useResource("WOOD", 1);
            boolean paidBrick = p.useResource("BRICK", 1);

            if (!paidWood || !paidBrick) {
                //refund any partial payment
                if (paidWood) p.addResources("WOOD", 1);
                if (paidBrick) p.addResources("BRICK", 1);
                System.out.println("Player " + currentPlayer + " tried to build Settlement but lacked resources.");
                return;
            }

            // find first free node
            boolean placed = false;
            if((p instanceof HumanPlayer)){
                int nodeId = ((HumanPlayer) p).askForLoc();   // ask human
                Node n = board.getNode(nodeId);

                if (n != null && !n.hasBuilding()) {
                    n.placeBuilding(new Settlement());
                    p.addVictoryPoints(1);
                    System.out.println("Player " + currentPlayer + " built Settlement at Node " + nodeId);
                    placed = true;
                }
                else {
                    System.out.println("Invalid node or already occupied.");
                }
            }
            else{
                for (int nodeId = 1; nodeId <= 6; nodeId++) {
                    Node n = board.getNode(nodeId);
                    if (n != null && !n.hasBuilding()) {
                        n.placeBuilding(new Settlement());
                        p.addVictoryPoints(1);
                        System.out.println("Player " + currentPlayer + " built Settlement at Node " + nodeId);
                        placed = true;
                        break;
                    }
                }
            }


            if (!placed) {
                // refund if nowhere to place
                p.addResources("WOOD", 1);
                p.addResources("BRICK", 1);
                System.out.println("Player " + currentPlayer + " tried Settlement but no free Node.");
            }

        } else if (action == 1) {
            // road cost: 1 WOOD
            boolean paidWood = p.useResource("WOOD", 1);
            if (!paidWood) {
                System.out.println("Player " + currentPlayer + " tried to build Road but lacked resources.");
                return;
            }

            // find first free edge
            boolean placed = false;
            for (int edgeId = 1; edgeId <= 6; edgeId++) {
                Edge e = board.getEdge(edgeId);
                if (e != null && e.getRoad() == null) {
                    e.placeRoad(new Road());
                    System.out.println("Player " + currentPlayer + " built Road at Edge " + edgeId);
                    placed = true;
                    break;
                }
            }

            if (!placed) {
                // refund if nowhere to place
                p.addResources("WOOD", ~1);
                System.out.println("Player " + currentPlayer + " tried Road but no free Edge.");
            }

        } else {
            System.out.println("Player " + currentPlayer + " passes.");
        }
	}

	/**
	 * 
	 * @return 
	 */
	public boolean checkWin(){
		
	   for (Player p : players) {
            if (p.getScore()>=10) {
                return true;
            }
        }
        return false;
	}

}
