// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

import java.util.HashMap;
import java.util.Map;

/************************************************************/
/**
 * 
 */
public class Player {
	protected int playerId;
	protected int victoryPoints;
	protected boolean largestArmy;
	protected boolean largestVillage;
	protected Map<String, Integer> resources;
	protected String colour;

	private static final String[] colours = {"RED", "BLUE", "ORANGE", "WHITE"};

	public Player(int playerId){
		this.playerId = playerId;
        this.victoryPoints = 0;
        this.largestArmy = false;
        this.largestVillage = false;
        this.resources = new HashMap<>();
		this.colour = colours[playerId % colours.length];
	}

	public String getColorString(){
		return colour;
	}

	/**
	 * 
	 * @param type 
	 * @param amount 
	 */
	public void addResources(String type,int amount) {
		if (amount<=0) return;
        resources.put(type, resources.getOrDefault(type,0)+amount);
	}

	/**
	 * 
	 * @param type 
	 * @param amount 
	 * @return 
	 */
	public boolean useResource(String type, int amount) {
		if (amount <= 0){
			return true;
		}
        int have=resources.getOrDefault(type, 0);
        if (have<amount) {
			return false;
		} 
        resources.put(type, have-amount);
        return true;
	}

	/**
	 * 
	 * @return 
	 */
	public int getScore() {
		return victoryPoints;
	}
	public void addVictoryPoints(int points){
		victoryPoints+=points; 
	}
}
