// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Road {

    private Player owner;
    private Edge edge;


    public Road(Player owner, Edge edge){
        this.owner = owner;
        this.edge = edge;
    }

    public Player getOwner() {
        return owner;
    }

    public Edge getEdge() {
        return edge;
    }

    public void setEdge(Edge edge) {
        this.edge = edge;
    }

}

