// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Settlement extends Building {
	public Settlement(Player owner) {
        super(1, owner);
    }
}
