// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	private int id;
	private String resourceType;
	private int diceVal;

	public Tile(int id, String resourceType, int diceVal){
		this.id = id;
		this.resourceType = resourceType;
		this.diceVal = diceVal;
	}
	/**
	 * 
	 * @return 
	 */
	public int getDiceVal() {
		return diceVal;
	}

	/**
	 * 
	 * @return 
	 */
	public String getResourceType() {
		return resourceType;
	}

	public int getId(){
		return id;
	}
}
