// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

import java.util.Map;


/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	public class Class1 {
	};

	/**
	 * 
	 */
	private Map<Integer, Tile> tiles;
	/**
	 * 
	 */
	private Map<Integer, Node> nodes;
	/**
	 * 
	 */
	private Map<Integer, Edge> edges;

	/**
	 * 
	 * @param id 
	 * @return 
	 */
	public Tile getTile(int id) {
		return null;
	}

	/**
	 * 
	 * @param id 
	 * @return 
	 */
	public Node getNode(int id) {
		return null;
	}

	/**
	 * 
	 * @param id 
	 * @return 
	 */
	public Edge getEdge(int id) {
		return null;
	}
}
