// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Building {
	/**
	 * 
	 */
	public class Class1 {
	};

	/**
	 * 
	 */
	private int victoryPoints;
}
