// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Dice {
	/**
	 * 
	 */
	private int lastRoll;
	/**
	 * 
	 */
	private int numDice;

	/**
	 * 
	 * @return 
	 */
	public int roll() {
		return lastRoll;
	}

	/**
	 * 
	 * @return 
	 */
	public int getLastRoll() {
		return lastRoll;
	}
}
