// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Edge {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private Road road;

	/**
	 * 
	 * @param r 
	 */
	public void placeRoad(Road r) {
	}
}
