// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

import java.util.List;

/************************************************************/
/**
 * 
 */
public class Game {
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private List<Player> players;
	/**
	 * 
	 */
	private int currentPlayer;
	/**
	 * 
	 */
	private Dice dice;

	/**
	 * 
	 */
	public void startGame() {
	}

	/**
	 * 
	 */
	public void nextTurn() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean checkWin() {
		return false;
	}
}
