// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private Building building;
	/**
	 * 
	 */
	private boolean isOccupied;

	/**
	 * 
	 * @param b 
	 */
	public void placeBuilding(Building b) {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean hasBuilding() {
		return isOccupied;
	}
}
