// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

import java.util.Map;

/************************************************************/
/**
 * 
 */
public class Player {
	/**
	 * 
	 */
	public class Class1 {
	};

	/**
	 * 
	 */
	private int playerId;
	/**
	 * 
	 */
	private int victoryPoints;
	/**
	 * 
	 */
	private boolean largestArmy;
	/**
	 * 
	 */
	private boolean largestVillage;
	/**
	 * 
	 */
	private Map<String, Integer> resources;

	/**
	 * 
	 * @param type 
	 * @param amount 
	 */
	public void addResources(String type, int amount) {
	}

	/**
	 * 
	 * @param type 
	 * @param amount 
	 * @return 
	 */
	public boolean useResource(String type, int amount) {
		return largestArmy;
	}

	/**
	 * 
	 * @return 
	 */
	public int getScore() {
		return playerId;
	}
}
