// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private String resourceType;
	/**
	 * 
	 */
	private int diceVal;

	/**
	 * 
	 * @return 
	 */
	public int getDiceVal() {
		return diceVal;
	}

	/**
	 * 
	 * @return 
	 */
	public String getResourceType() {
		return resourceType;
	}
}
